; NetLister Settings File
;
;
; Each setting section must start with "ftn_" or "qwk_" and the name of the 
; network enclosed in square brackets.
; 
; Valid FTN settings are:
; 
;  text ....... This is the visible menu option. Include an ampersand (&) in
;               front of the character you want to use as a hotkey. 
; 
;               If omitted, the string to the right of the underscore is used
;               by default.
;
;  nodelist ... This is the path to the nodelist for the FTN.
;
;               nodelist may be:
;               - A path to a static nodelist file (typically the same as what
;                 you configured in FidoCFG under Domains).
;               - A path to a static nodelist archive.
;               - A path to a directory containing nodelist files or archives.
;                 The newest one will be selected automatically.
;
;               If nodelist is invalid, the FTN will be ignored.
;
;  art ........ This is a path to an ANSI file or CTRL-A file to display with 
;               the FTN menus. This could be artwork from the infopack for the 
;               net. Pick your favorite one available (or make your own) and 
;               store it somewhere, then set your path to it here. The first 10 
;               rows will be visible. If left blank, the NetLister main menu art 
;               gets used by default.
; 
;
; Example FTN setting:
;
; [ftn_FidoNet]
; text=&FidoNet
; nodelist=c:\path\to\NODELIST.txt
; art=c:\path\to\hdr-fidonet.ans
;
; Add as many listings as you have FTNs and nodelists.
;
;
; 
; Valid QWK settings are:
; 
;  text ....... Same as with FTN setting above.
;
;  id ......... This is the Hub System ID as configured for the QWK Network
;               in SCFG.
;
;  art ........ Same as with FTN setting above.
;
;
; Example QWK setting:
;
; [qwk_DOVE-Net]
; text=&DOVE-Net
; id=VERT
; art=c:\path\to\hdr-dovenet.ans
;
; If you need an ANSI file for DOVE-Net, look for dove-net_logos.zip.
;
; Add as many listings as you have QWK networks. The script should find as many
; QWK nodes that Synchronet is aware of.
;


[ftn_FidoNet]
text=&FidoNet
nodelist=c:\path\to\NODELIST.txt
art=c:\path\to\hdr-fidonet.ans

[qwk_DOVE-Net]
text=&DOVE-Net
id=VERT
art=c:\path\to\hdr-dovenet.ans
